### ISSUE TITLE
Ubuntu 16.04: missing libboost_system.so.1.54.0

### ISSUE THREAD

**Issue by drpoom** [altcommunitycoin/SONO#1]
File:
SONO-linux-qt release 1.2

Findings:
./SONO-linux-qt 
./SONO-linux-qt: error while loading shared libraries: libboost_system.so.1.54.0: cannot open shared object file: No such file or directory

Comments:
and it seems like the binary requires libboost 1.54, and will give such errrors when 1.58 is installed.

**Comment by theflu** [comment]
Try installing libboost.

`sudo apt-get install libboost-all-dev`

**Comment by altcommunitycoin** [comment]
You can run the install-dependencies script - that should solve this issue

`cd SONO`
`chmod +x install-dependencies.sh`
`./install-dependencies.sh`

**Comment by tgwaste** [comment]
Are you freaking kidding me?  Why all of the sudden do we need all of this puke on our systems?

The following NEW packages will be installed:
  libboost-all-dev libboost-atomic-dev libboost-atomic1.62-dev libboost-atomic1.62.0 libboost-chrono-dev libboost-chrono1.62-dev
  libboost-chrono1.62.0 libboost-context-dev libboost-context1.62-dev libboost-context1.62.0 libboost-coroutine-dev
  libboost-coroutine1.62-dev libboost-coroutine1.62.0 libboost-date-time-dev libboost-date-time1.62-dev libboost-date-time1.62.0
  libboost-dev libboost-exception-dev libboost-exception1.62-dev libboost-fiber-dev libboost-fiber1.62-dev libboost-fiber1.62.0
  libboost-filesystem-dev libboost-filesystem1.62-dev libboost-filesystem1.62.0 libboost-graph-dev libboost-graph-parallel-dev
  libboost-graph-parallel1.62-dev libboost-graph-parallel1.62.0 libboost-graph1.62-dev libboost-graph1.62.0 libboost-iostreams-dev
  libboost-iostreams1.62-dev libboost-iostreams1.62.0 libboost-locale-dev libboost-locale1.62-dev libboost-locale1.62.0
  libboost-log-dev libboost-log1.62-dev libboost-log1.62.0 libboost-math-dev libboost-math1.62-dev libboost-math1.62.0
  libboost-mpi-dev libboost-mpi-python-dev libboost-mpi-python1.62-dev libboost-mpi-python1.62.0 libboost-mpi1.62-dev
  libboost-mpi1.62.0 libboost-python-dev libboost-python1.62-dev libboost-python1.62.0 libboost-random-dev libboost-random1.62-dev
  libboost-random1.62.0 libboost-regex-dev libboost-regex1.62-dev libboost-regex1.62.0 libboost-serialization-dev
  libboost-serialization1.62-dev libboost-serialization1.62.0 libboost-signals-dev libboost-signals1.62-dev libboost-signals1.62.0
  libboost-test-dev libboost-test1.62-dev libboost-test1.62.0 libboost-thread-dev libboost-thread1.62-dev libboost-thread1.62.0
  libboost-timer-dev libboost-timer1.62-dev libboost-timer1.62.0 libboost-tools-dev libboost-type-erasure-dev
  libboost-type-erasure1.62-dev libboost-type-erasure1.62.0 libboost-wave-dev libboost-wave1.62-dev libboost-wave1.62.0
  libboost1.62-tools-dev libfabric1 libhwloc-dev libhwloc-plugins libhwloc5 libibverbs-dev libibverbs1 libnl-3-200
  libnl-route-3-200 libnuma-dev libopenmpi-dev libopenmpi2 libpsm-infinipath1 libpython3-dev libpython3.5-dev librdmacm1
  mpi-default-bin mpi-default-dev ocl-icd-libopencl1 openmpi-bin openmpi-common python3-dev python3.5-dev

**Comment by Swjtu-only** [comment]
sudo apt-get install libboost-all-dev
and then
sudo make clean
sudo make .....   -j100
